services:
  app:
    environment:
      - DEV_MODE=true
      - AUTO_START_SCHEDULER=true
    command: >
      sh -c "python -m migrations.runner &&
      exec gunicorn --bind 0.0.0.0:5001 --workers 1 --threads 4 --reload main:app"
    volumes:
      - .:/app

  db:
    ports:
      - "5434:5432"
