"""Independent suite for issue #98, generated by qwen/qwen3.8-max via OpenRouter.

Written by a model family that had no part in the service or in the fix, so it
is a genuine second opinion rather than a restatement of our own reasoning.
Provenance and the operator edits are recorded at the bottom of this docstring.

Test suite for GitHub issue #98: PropertyTravelService.calculate_for_property()
must distinguish API failures from genuine "nothing nearby" results.

DEFECT: The current implementation returns True and stores status="not_found"
even when every Google API call was refused (REQUEST_DENIED, OVER_QUERY_LIMIT,
HTTP errors, missing key). This is indistinguishable from a legitimate
"the API answered and there is genuinely nothing nearby" result.

CONTRACT (what the code SHOULD do):
- If all Places calls are refused, calculate_for_property() must return False.
- The stored travel JSON must use a status that is NOT "not_found" for API errors.
  Acceptable error statuses include "error", "api_error", "request_denied", etc.
- If the API answers normally but finds nothing, that IS success: return True,
  store status="not_found".
- Partial failures (Places down, Distance Matrix up) must be surfaced honestly.

Measured, not asserted: against 69566e1 (the commit before the fix) 11 of these
16 tests fail; against the merged fix all 16 pass. The 5 that pass on both are
the controls that a heavy-handed fix would have broken.

Operator edits, disclosed so the model's contribution stays legible:

Mechanical corrections to what was generated
  - `source_email_id` added to the fixture (NOT NULL in this schema).
  - `_targets()`: the generated assertions walked `travel.items()`, but
    per-target outcomes live under `travel["targets"]`. At the wrong level four
    loops asserted nothing at all and two more failed on both trees.
  - The service was built with only a Places key, so it never reached Distance
    Matrix and every run silently took the straight-line estimate branch. Both
    keys are passed now, except where a missing key is the subject.
  - `_distance_matrix_ok_response` carried a duration but no distance, which
    the service cannot use - the "healthy" reply produced status="estimated".

From the review of this suite (three findings, all fair)
  - `assert_every_target_reports_a_refusal` replaces walks shaped
    `if travel: ... if "status" in val: assert ...`, which an empty
    `{"targets": {}}` satisfied without comparing anything.
  - The happy path accepted `{"school": {}}`; it now requires a travel time.
  - `TestZeroResultsIsAnAnswer`: the "nothing nearby" control used
    `status="OK"`, but Google sends ZERO_RESULTS. A fix that read every non-OK
    status as an outage would have passed the suite as generated.

Operator-authored, because the model lacked the config shape
  - `TestPlacesRefusedWhileDistanceMatrixAnswers`: the real mixed case. Its own
    reasoning trace flagged that presets alone cannot express it.

No scenario the model asked for was removed, and no expectation was weakened
to fit the implementation.
"""

from unittest.mock import MagicMock, patch

import pytest

# --- Project bootstrap (assumed to exist per project conventions) ---
from tests import setup_test_environment

setup_test_environment()

from app import create_app, db  # noqa: E402
from models import Property  # noqa: E402


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

PLACES_URL = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
DISTANCE_MATRIX_URL = "https://maps.googleapis.com/maps/api/distancematrix/json"

# A minimal preset definition that the service will iterate over.
FAKE_PRESET_DEFS = [
    {
        "key": "school",
        "label": "Nearest school",
        "place_types": ["school"],
    }
]

FAKE_TRAVEL_CONFIG = {
    "presets": {
        "school": {"enabled": True, "mode": "driving"},
    },
    "custom": [],
}


def _targets(travel):
    """Per-target outcomes live under travel["targets"], not at the top level.

    Operator correction, not the model's: the generated assertions walked
    travel.items() directly, where no entry carries a "status" key, so four
    loops never executed a single assertion and two more failed on both the
    fixed and the broken tree. Reading the right level makes them real.
    """
    if not isinstance(travel, dict):
        return {}
    return travel.get("targets") or {}


def assert_every_target_reports_a_refusal(travel, context):
    """Assert positively: at least one target, and none of them "not_found".

    Operator addition. The generated assertions were shaped as
    `if travel: for ... : if "status" in val: assert ...`, which an empty
    `{"targets": {}}` satisfies without comparing anything - the suite would
    pass while proving nothing was recorded at all.
    """
    targets = _targets(travel)
    assert targets, (
        f"{context}: nothing was persisted, so the refusal was not recorded "
        f"anywhere a reader could find it. travel={travel!r}"
    )
    for key, val in targets.items():
        assert isinstance(val, dict) and "status" in val, (
            f"{context}: target '{key}' has no status at all: {val!r}"
        )
        assert val["status"] != "not_found", (
            f"{context}: target '{key}' says 'not_found', which is what a real "
            f"answer with nothing nearby says. A refusal must be distinguishable."
        )


def _make_response(status_code=200, json_data=None):
    """Build a fake requests.Response-like object."""
    resp = MagicMock()
    resp.status_code = status_code
    resp.json.return_value = json_data or {}
    return resp


def _places_ok_response(results=None):
    """A healthy Places response with optional results."""
    return _make_response(200, {"status": "OK", "results": results or []})


def _places_denied_response():
    """Places returns REQUEST_DENIED (e.g. bad key)."""
    return _make_response(200, {"status": "REQUEST_DENIED", "results": []})


def _places_over_limit_response():
    """Places returns OVER_QUERY_LIMIT."""
    return _make_response(200, {"status": "OVER_QUERY_LIMIT", "results": []})


def _distance_matrix_ok_response():
    """A healthy Distance Matrix response.

    Operator correction: as generated the element carried a duration but no
    distance, which the service cannot use - it fell back to a straight-line
    estimate and recorded status="estimated". The happy-path test then passed
    while never exercising the happy path. A real reply carries both.
    """
    return _make_response(
        200,
        {
            "status": "OK",
            "rows": [
                {
                    "elements": [
                        {
                            "status": "OK",
                            "distance": {"value": 4200, "text": "4.2 km"},
                            "duration": {"value": 600, "text": "10 mins"},
                        }
                    ]
                }
            ],
            "destination_addresses": ["123 Main St"],
            "origin_addresses": ["456 Oak Ave"],
        },
    )


@pytest.fixture
def app():
    """Create a fresh Flask app in testing mode with an in-memory DB."""
    application = create_app(testing=True)
    with application.app_context():
        db.create_all()
        yield application
        db.session.remove()
        db.drop_all()


@pytest.fixture
def prop(app):
    """Create a minimal Property with coordinates so ensure_coordinates is trivially true."""
    # Adaptation by the operator, not the model: source_email_id is NOT NULL in
    # this schema, which the prompt did not say. No assertion was touched.
    p = Property(
        source_email_id="qwen-test-1",
        title="Test Property",
        url="https://example.com/test",
        location_lat=51.5074,
        location_lon=-0.1278,
    )
    db.session.add(p)
    db.session.commit()
    return p


def _patch_service_deps(mock_request, mock_cache, mock_preset_defs, mock_travel_config):
    """Apply the standard set of patches and return the service instance."""
    from services.property_travel_service import PropertyTravelService

    svc = PropertyTravelService(
        google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY_FOR_TESTING"
    )

    # Stub location_service so no geocoding happens
    svc.location_service = MagicMock()
    svc.location_service.ensure_coordinates.return_value = True

    return svc


# ---------------------------------------------------------------------------
# Test 1: All Places calls refused with REQUEST_DENIED
# ---------------------------------------------------------------------------


class TestAllPlacesRefused:
    """
    When every Places call returns REQUEST_DENIED, the service must NOT
    report success. The current code returns True and stores "not_found",
    which is the bug.
    """

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_returns_false_when_all_places_denied(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: calculate_for_property() returns False when Places is REQUEST_DENIED.
        FAILS TODAY: current code returns True.
        """
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        # Every network call returns REQUEST_DENIED
        mock_request.return_value = _places_denied_response()

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        result = svc.calculate_for_property(prop, commit=True)

        # The fix must make this False — the service should not claim success
        # when every API call was refused.
        assert result is False, (
            "calculate_for_property() returned True even though every Places "
            "call was REQUEST_DENIED. It must return False to signal failure."
        )

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_travel_json_distinguishes_denied_from_not_found(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: The stored travel JSON must NOT use status="not_found" when
        the API refused the request. It should use a distinct error status.
        FAILS TODAY: current code stores "not_found" for both cases.
        """
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        mock_request.return_value = _places_denied_response()

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        svc.calculate_for_property(prop, commit=True)

        # Reload from DB to see what was persisted
        db.session.refresh(prop)
        travel = prop.travel

        # The status must NOT be "not_found": the API never searched, it refused.
        assert_every_target_reports_a_refusal(
            travel, "every Places call REQUEST_DENIED"
        )


# ---------------------------------------------------------------------------
# Test 2: Places refused but Distance Matrix healthy (partial failure)
# ---------------------------------------------------------------------------


class TestPartialFailure:
    """
    Real-world scenario from the day the bug was found: Places returned
    REQUEST_DENIED (old key in env var) while Distance Matrix answered OK.
    The service must surface the Places failure honestly.
    """

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_places_denied_distance_matrix_ok_reports_failure(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: When Places is denied but Distance Matrix would work,
        the method must return False (no destinations were found).
        FAILS TODAY: returns True with "not_found" status.
        """
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        def side_effect(fn, url, **kwargs):
            if "place/nearbysearch" in url:
                return _places_denied_response()
            elif "distancematrix" in url:
                return _distance_matrix_ok_response()
            return _make_response(404, {})

        mock_request.side_effect = side_effect

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        result = svc.calculate_for_property(prop, commit=True)

        # Places failed → no destinations found → no travel times computed.
        # The method must not pretend this was a success.
        assert result is False, (
            "calculate_for_property() returned True even though Places was "
            "REQUEST_DENIED. Distance Matrix being healthy doesn't help if "
            "we never found any destinations. Must return False."
        )

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_partial_failure_travel_json_has_error_status(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: In the partial-failure case, the travel JSON must record
        an error status for the Places-dependent targets, not "not_found".
        FAILS TODAY: stores "not_found".
        """
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        def side_effect(fn, url, **kwargs):
            if "place/nearbysearch" in url:
                return _places_denied_response()
            elif "distancematrix" in url:
                return _distance_matrix_ok_response()
            return _make_response(404, {})

        mock_request.side_effect = side_effect

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        svc.calculate_for_property(prop, commit=True)
        db.session.refresh(prop)

        assert_every_target_reports_a_refusal(
            prop.travel, "Places REQUEST_DENIED while Distance Matrix answers"
        )


# ---------------------------------------------------------------------------
# Test 3: Genuine "nothing nearby" — this IS success (control test)
# ---------------------------------------------------------------------------


class TestGenuineNothingNearby:
    """
    CONTROL: When the API answers normally (status=OK) but returns an empty
    results list, that is a legitimate "nothing nearby". The method MUST
    return True and store "not_found". An over-eager fix that makes ALL
    empty results look like errors would break this.
    """

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_genuine_empty_results_is_success(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: API returns OK with empty results → method returns True.
        This must PASS both before and after the fix.
        """
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        # Places answers normally but finds nothing
        mock_request.return_value = _places_ok_response(results=[])

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        result = svc.calculate_for_property(prop, commit=True)

        # This IS a successful enrichment run — the API worked, there's just
        # nothing nearby. Must return True.
        assert result is True, (
            "calculate_for_property() returned False even though the API "
            "answered OK with empty results. A genuine 'nothing nearby' is "
            "a valid, successful result."
        )

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_genuine_empty_results_stores_not_found(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: Genuine empty results → travel JSON has status="not_found".
        This must PASS both before and after the fix.
        """
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        mock_request.return_value = _places_ok_response(results=[])

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        svc.calculate_for_property(prop, commit=True)
        db.session.refresh(prop)

        travel = prop.travel
        assert travel is not None, "Travel JSON should be written on success."

        # At least one target should have status "not_found"
        found_not_found = False
        if isinstance(travel, dict):
            for key, val in _targets(travel).items():
                if isinstance(val, dict) and val.get("status") == "not_found":
                    found_not_found = True
                    break

        assert found_not_found, (
            "When the API genuinely finds nothing, the travel JSON should "
            "contain status='not_found'. This is the legitimate use of that status."
        )


# ---------------------------------------------------------------------------
# Test 4: HTTP-level failure (timeout, 500)
# ---------------------------------------------------------------------------


class TestHTTPLevelFailure:
    """
    An HTTP 500 or a timeout is different from an API-level refusal.
    Both are errors, but both must be distinguishable from "not_found".
    """

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_http_500_returns_false(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: HTTP 500 from Places → method returns False.
        FAILS TODAY: returns True with "not_found".
        """
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        mock_request.return_value = _make_response(
            500, {"error": "Internal Server Error"}
        )

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        result = svc.calculate_for_property(prop, commit=True)

        assert result is False, (
            "calculate_for_property() returned True even though Places "
            "returned HTTP 500. Must return False."
        )

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_http_500_travel_json_not_not_found(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: HTTP 500 → travel JSON must not say "not_found".
        FAILS TODAY: stores "not_found".
        """
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        mock_request.return_value = _make_response(500, {})

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        svc.calculate_for_property(prop, commit=True)
        db.session.refresh(prop)

        assert_every_target_reports_a_refusal(prop.travel, "Places returned HTTP 500")

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_timeout_exception_returns_false(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: If request_with_retries raises (e.g. ConnectionError, Timeout),
        the method must return False.
        FAILS TODAY: the exception is swallowed per-place and the method
        still returns True.
        """
        import requests as req_lib

        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        mock_request.side_effect = req_lib.exceptions.Timeout("Connection timed out")

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        result = svc.calculate_for_property(prop, commit=True)

        assert result is False, (
            "calculate_for_property() returned True even though every request "
            "timed out. Must return False."
        )


# ---------------------------------------------------------------------------
# Test 5: OVER_QUERY_LIMIT — load-bearing because it's the most common
#          silent failure mode in production (quota exhaustion).
# ---------------------------------------------------------------------------


class TestOverQueryLimit:
    """
    OVER_QUERY_LIMIT is the most insidious failure: it looks like a valid
    API response (HTTP 200, parseable JSON) but means nothing was searched.
    It must be treated as an error, not "not_found".
    """

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_over_query_limit_returns_false(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: OVER_QUERY_LIMIT → method returns False.
        FAILS TODAY: returns True.
        """
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        mock_request.return_value = _places_over_limit_response()

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        result = svc.calculate_for_property(prop, commit=True)

        assert result is False, (
            "calculate_for_property() returned True even though Places "
            "returned OVER_QUERY_LIMIT. Must return False."
        )

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_over_query_limit_travel_json_not_not_found(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: OVER_QUERY_LIMIT → travel JSON must not say "not_found".
        FAILS TODAY: stores "not_found".
        """
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        mock_request.return_value = _places_over_limit_response()

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        svc.calculate_for_property(prop, commit=True)
        db.session.refresh(prop)

        assert_every_target_reports_a_refusal(
            prop.travel, "Places returned OVER_QUERY_LIMIT"
        )


# ---------------------------------------------------------------------------
# Test 6: Missing API key — load-bearing because it's a configuration error,
#          not a runtime API failure. The current code uses "no_places_key"
#          which is at least distinguishable, but the method still returns True.
# ---------------------------------------------------------------------------


class TestMissingAPIKey:
    """
    When no API key is configured, the service cannot possibly succeed.
    It must return False. The current code returns True with status
    "no_places_key" — the status is arguably fine, but returning True
    is the bug.
    """

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_missing_key_returns_false(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: No API key → method returns False.
        FAILS TODAY: returns True.
        """
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        from services.property_travel_service import PropertyTravelService

        # Explicitly pass empty/None key
        svc = PropertyTravelService(google_places_key="")
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        result = svc.calculate_for_property(prop, commit=True)

        assert result is False, (
            "calculate_for_property() returned True even though no Places API "
            "key is configured. Must return False."
        )


# ---------------------------------------------------------------------------
# Test 7: Full success path — Places finds something, Distance Matrix works.
#          This is the happy-path control that must not break.
# ---------------------------------------------------------------------------


class TestFullSuccessPath:
    """
    CONTROL: Everything works. Places finds a school, Distance Matrix
    computes travel time. Method returns True, travel JSON has actual data.
    Must PASS both before and after the fix.
    """

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_full_success_returns_true(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: Happy path → method returns True.
        Must PASS before and after the fix.
        """
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        places_result = {
            "name": "Test School",
            "place_id": "ChIJ123",
            "types": ["school"],
            "geometry": {"location": {"lat": 51.51, "lng": -0.13}},
        }

        def side_effect(fn, url, **kwargs):
            if "place/nearbysearch" in url:
                return _places_ok_response(results=[places_result])
            elif "distancematrix" in url:
                return _distance_matrix_ok_response()
            return _make_response(404, {})

        mock_request.side_effect = side_effect

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        result = svc.calculate_for_property(prop, commit=True)

        assert result is True, (
            "calculate_for_property() returned False on the happy path. "
            "When everything works, it must return True."
        )

    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_full_success_travel_has_place_data(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """
        ASSERT: Happy path → travel JSON contains place info and/or travel time.
        Must PASS before and after the fix.
        """
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG

        places_result = {
            "name": "Test School",
            "place_id": "ChIJ123",
            "types": ["school"],
            "geometry": {"location": {"lat": 51.51, "lng": -0.13}},
        }

        def side_effect(fn, url, **kwargs):
            if "place/nearbysearch" in url:
                return _places_ok_response(results=[places_result])
            elif "distancematrix" in url:
                return _distance_matrix_ok_response()
            return _make_response(404, {})

        mock_request.side_effect = side_effect

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        svc.calculate_for_property(prop, commit=True)
        db.session.refresh(prop)

        travel = prop.travel
        assert travel is not None, "Travel JSON must be written on success."

        # Operator strengthening: as generated, this accepted `{"school": {}}` -
        # a happy path that persisted nothing at all would have passed. The
        # point of the run is the travel time, so assert the travel time.
        school_data = _targets(travel).get("school")
        assert school_data, f"expected a 'school' target with data, got {travel!r}"
        assert school_data.get("status") not in {"not_found", "unavailable"}, (
            f"the happy path must not record a failure state: {school_data!r}"
        )
        assert school_data.get("duration_min") is not None, (
            f"a resolved target without a duration is an empty result wearing a "
            f"success label: {school_data!r}"
        )


# ---------------------------------------------------------------------------
# Operator addition, from the review of this suite: ZERO_RESULTS.
#
# The generated control used status="OK" with an empty results list, but that
# is not what Google sends when a search finds nothing - it sends
# ZERO_RESULTS. A fix that treated every non-OK status as a refusal would
# reclassify "no school within range" as an outage, and the suite as written
# would not have noticed. This is the control the control was missing.
# ---------------------------------------------------------------------------


def _places_zero_results_response():
    """What Google actually returns for a search that found nothing."""
    return _make_response(200, {"status": "ZERO_RESULTS", "results": []})


class TestZeroResultsIsAnAnswer:
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_zero_results_is_success_and_not_a_refusal(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """ASSERT: ZERO_RESULTS is an answer - success, and "not_found", not an error."""
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = FAKE_TRAVEL_CONFIG
        mock_request.return_value = _places_zero_results_response()

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        result = svc.calculate_for_property(prop, commit=True)
        db.session.refresh(prop)

        assert result is True, (
            "ZERO_RESULTS means Google searched and found nothing. That is a "
            "successful run over empty ground, not a failure."
        )
        school = _targets(prop.travel).get("school")
        assert school, f"expected a 'school' target, got {prop.travel!r}"
        assert school.get("status") == "not_found", (
            f"ZERO_RESULTS must record the genuine 'nothing nearby' state, not an "
            f"API error: {school!r}"
        )


# ---------------------------------------------------------------------------
# Operator addition: the genuinely mixed case.
#
# The model asked for "Places refused while Distance Matrix answers" and wrote
# it with presets only - but a preset target needs Places to find a place, so a
# refusal there leaves nothing to route to and Distance Matrix is never called.
# Its own reasoning trace flagged this and guessed at a custom-target config it
# had not been shown. A custom target carries its own coordinates, so it routes
# without Places, and both APIs are exercised in one run: exactly the shape of
# the 2026-08-08 outage, where the Places key was stale and the Maps key was not.
# ---------------------------------------------------------------------------

MIXED_TRAVEL_CONFIG = {
    "presets": {"school": {"enabled": True, "mode": "driving"}},
    "custom": [{"name": "Office", "lat": 51.52, "lon": -0.14, "mode": "driving"}],
}


class TestPlacesRefusedWhileDistanceMatrixAnswers:
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_targets_config"
    )
    @patch(
        "services.property_travel_service.SearchProfileService.get_travel_preset_defs"
    )
    @patch("services.property_travel_service.get_cached_enrichment_data")
    @patch("services.property_travel_service.request_with_retries")
    def test_one_refusal_and_one_answer_are_both_visible(
        self, mock_request, mock_cache, mock_preset_defs, mock_travel_config, app, prop
    ):
        """ASSERT: a partial outage is neither reported as total success nor as total failure."""
        mock_cache.return_value = None
        mock_preset_defs.return_value = FAKE_PRESET_DEFS
        mock_travel_config.return_value = MIXED_TRAVEL_CONFIG

        def side_effect(_fn, url, **_kwargs):
            if "place/nearbysearch" in url:
                return _places_denied_response()
            if "distancematrix" in url:
                return _distance_matrix_ok_response()
            return _make_response(404, {})

        mock_request.side_effect = side_effect

        from services.property_travel_service import PropertyTravelService

        svc = PropertyTravelService(
            google_maps_key="FAKE_MAPS_KEY", google_places_key="FAKE_KEY"
        )
        svc.location_service = MagicMock()
        svc.location_service.ensure_coordinates.return_value = True

        result = svc.calculate_for_property(prop, commit=True)
        db.session.refresh(prop)

        called = [c.args[1] for c in mock_request.call_args_list]
        assert any("place/nearbysearch" in u for u in called), (
            "the premise of this test is that Places was called and refused"
        )
        assert any("distancematrix" in u for u in called), (
            f"Distance Matrix was never called, so nothing here proves it stayed "
            f"healthy while Places did not. URLs: {called}"
        )

        targets = _targets(prop.travel)
        school = targets.get("school")
        custom = next(
            (v for k, v in targets.items() if str(k).startswith("custom:")), None
        )

        assert school and school.get("status") != "not_found", (
            f"the Places refusal must not read as 'nothing nearby': {school!r}"
        )
        assert custom and custom.get("duration_min") is not None, (
            f"the target that did not need Places must still have its travel "
            f"time - a partial outage must not discard the half that worked: "
            f"{custom!r}"
        )
        assert result is True, (
            "one target resolved, so the run is degraded rather than failed; "
            "returning False here would tell the caller to discard a good result"
        )
