"""The curated agency table behind ``/agencies`` (owner request, 2026-08-22).

The page answers one question -- *which agencies hold the most detached houses
up to 300 000 EUR in Asturias and Cantabria* -- and its source of truth is
``data/top_agencies.json``, a committed, hand-reviewed file in the same family
as ``data/ine_municipal.json``: small, regenerated by a person, re-included in
``.gitignore`` by name.

Two things about it are deliberate.  The figures are a **measurement taken on a
date** -- counts read off idealista microsites and fotocasa agency pages with
the filters applied -- and not a live feed; the file carries ``measured_at`` and
the page prints it, because a number without its date would read as today's.
And a missing or unreadable file is **reported as such**, never rendered as an
empty table: an empty table says "no agencies", which is the opposite of "nobody
can read the file" (the #98 rule, applied to a reference file).
"""

from __future__ import annotations

import json
import logging
import os

logger = logging.getLogger(__name__)

_DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")
TOP_AGENCIES_PATH = os.path.join(_DATA_DIR, "top_agencies.json")


class AgencyDataUnavailable(Exception):
    """``data/top_agencies.json`` is missing, unreadable or malformed."""


def _int_or_none(value) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    return None


def _normalise(agency: dict) -> dict:
    """One row, with every optional block present so the template never guesses.

    ``idealista.detached`` is the ranking key (chalets independientes + casas
    rusticas, <= 300k); ``independientes`` and ``casas_chalets`` are shown next
    to it so a reader who means only *chalet independiente* can re-rank by eye.
    """
    idealista = dict(agency.get("idealista") or {})
    fotocasa = dict(agency.get("fotocasa") or {})
    reviews = dict(agency.get("reviews") or {})
    return {
        "name": str(agency.get("name") or "").strip(),
        "region": agency.get("region") or "",
        "base": agency.get("base") or "",
        "founded": agency.get("founded") or None,
        "website": agency.get("website") or None,
        "phone": agency.get("phone") or None,
        "description": agency.get("description") or "",
        "idealista": {
            "detached": _int_or_none(idealista.get("detached")),
            "independientes": _int_or_none(idealista.get("independientes")),
            "casas_chalets": _int_or_none(idealista.get("casas_chalets")),
            "url": idealista.get("url") or None,
            "url_secondary": idealista.get("url_secondary") or None,
            "secondary_label": idealista.get("secondary_label") or None,
        },
        "fotocasa": {
            "count": _int_or_none(fotocasa.get("count")),
            "url": fotocasa.get("url") or None,
            "note": fotocasa.get("note") or None,
        },
        "reviews": {
            "google_rating": reviews.get("google_rating")
            if isinstance(reviews.get("google_rating"), (int, float))
            and not isinstance(reviews.get("google_rating"), bool)
            else None,
            "google_count": _int_or_none(reviews.get("google_count")),
            "source": reviews.get("source") or None,
            "note": reviews.get("note") or None,
        },
        "other_links": [
            {"label": str(link.get("label") or "link"), "url": link["url"]}
            for link in (agency.get("other_links") or [])
            if isinstance(link, dict) and link.get("url")
        ],
        "notes": agency.get("notes") or "",
    }


def load_top_agencies(path: str | None = None) -> dict:
    """Read the table, rank it by ``idealista.detached`` (desc) and return it.

    Raises ``AgencyDataUnavailable`` for a missing, unreadable or malformed
    file -- callers refuse the page rather than drawing an empty one.
    """
    target = path or TOP_AGENCIES_PATH
    try:
        with open(target, encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, ValueError) as exc:
        raise AgencyDataUnavailable(f"{target}: {exc}") from exc

    if not isinstance(data, dict):
        raise AgencyDataUnavailable(f"{target}: top-level value is not an object")
    measured_at = data.get("measured_at")
    agencies = data.get("agencies")
    if not isinstance(measured_at, str) or not measured_at.strip():
        raise AgencyDataUnavailable(f"{target}: missing measured_at")
    if not isinstance(agencies, list):
        raise AgencyDataUnavailable(f"{target}: 'agencies' is not a list")

    rows = [_normalise(a) for a in agencies if isinstance(a, dict)]
    rows = [r for r in rows if r["name"]]
    # Unmeasured rows (no idealista count) sort last, the way the listing
    # table and /municipalities treat an absent measurement.
    rows.sort(
        key=lambda r: (
            r["idealista"]["detached"] is None,
            -(r["idealista"]["detached"] or 0),
            r["name"].lower(),
        )
    )
    for rank, row in enumerate(rows, start=1):
        row["rank"] = rank

    return {
        "measured_at": measured_at.strip(),
        "criteria": data.get("criteria")
        if isinstance(data.get("criteria"), dict)
        else {},
        "method": data.get("method") or "",
        "agencies": rows,
    }
